spring:
  datasource:
    url: jdbc:postgresql://ec2-52-206-182-219.compute-1.amazonaws.com:5432/d6ttdkb120qabe
    username: ksesatralyugmi
    driver-class-name: org.postgresql.Driver
    password: 2977d8032df70478ca040195618f1fdb435309de961b3c95ce2a91b0bd3ee0b1
#    url: jdbc:postgresql://localhost:5432/talk_on
#    username: postgres
#    password: root123

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      #      mode: always
      mode: never

server:
  port: 9090

api:
  info:
    title: TalkOn
    description: Online queue
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: 000
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /docs

service:
  prop:
    protocol: https
    ip: tolkon-2022.herokuapp.com
    url: boom.uz

#service:
#  prop:
#    protocol: http
#    ip: localhost
#    port: 9090
#    url: boom.uz



app:
  base:
    api: /api
  version: /v1
