spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/talk_on
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
#      mode: always
      mode: never

server:
  port: 9090

api:
  info:
    title: TalkOn
    description: Online queue
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: 000
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /docs

service:
  prop:
    protocol: http
    ip: localhost
    port: 9090
    url: boom.uz


app:
  base:
    api: /api
  version: /v1
